version: "3"
services:
    backend:
        build:
            context: .
            args:
                - NODE_ENV=production
        environment:
            - NODE_ENV=production
        command: npm start

    nginx:
        ports:
            - 80:80
