version: "3"
services:
    backend:
        build:
            context: .

        environment:
            - NODE_ENV=production
            - SESSION_SECRET=${SESSION_SECRET}

        command: npm start

    nginx:
        ports:
            - 80:80
