version: "3"
services:
    backend:
        # custom img
        build: .
        environment:
            - PORT=3000
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=uttam
            - MONGO_INITDB_ROOT_PASSWORD=171210
        volumes:
            # named volume
            - mongo-db:/data/db

    redis:
        image: redis

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# have to put all named volumes here because there may be many services using this mongo-db volume
volumes:
    mongo-db:
