version: "3"
services:
    backend:
        # custom img
        build: .
        # by passing image name, we can use both approach of build the image from Dockerfile or can pull from dockerhub
        image: uttam1712/node-app
        environment:
            - PORT=3000
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo
        volumes:
            # named volume
            - mongo-db:/data/db

    redis:
        image: redis

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# have to put all named volumes here because there may be many services using this mongo-db volume
volumes:
    mongo-db:
